services:
  nginx:
    image: ghcr.io/usamg1t/tcp-web/nginx:latest
    container_name: tcp-simulator-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginx-logs:/var/log/nginx
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - tcp-simulator-network

  backend:
    image: ghcr.io/usamg1t/tcp-web/backend:latest
    container_name: tcp-simulator-backend
    expose:
      - "5000"
    restart: unless-stopped
    networks:
      - tcp-simulator-network

networks:
  tcp-simulator-network:
    driver: bridge

volumes:
  nginx-logs:
