services:
  web:
    image: ghcr.io/usamg1t/tcp-web/web:latest
    container_name: tcp-simulator-web
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - tcp-simulator-network

  backend:
    image: ghcr.io/usamg1t/tcp-web/backend:latest
    container_name: tcp-simulator-backend
    ports:
      - "5000:5000"          # REST API exposed directly on the port
    restart: unless-stopped
    networks:
      - tcp-simulator-network

networks:
  tcp-simulator-network:
    driver: bridge
